# Generated by Django 3.1.2 on 2020-10-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('vehicle_id', models.IntegerField()),
                ('package_id', models.FloatField()),
                ('travel_type_id', models.IntegerField()),
                ('from_area_id', models.FloatField()),
                ('to_area_id', models.FloatField()),
                ('from_city_id', models.FloatField()),
                ('to_city_id', models.FloatField()),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('online_booking', models.BooleanField()),
                ('mobile_site_booking', models.BooleanField()),
                ('booking_created', models.DateTimeField()),
                ('from_lat', models.FloatField()),
                ('from_long', models.FloatField()),
                ('to_lat', models.FloatField()),
                ('to_long', models.FloatField()),
                ('car_cancellation', models.BooleanField()),
            ],
        ),
    ]
