# Generated by Django 3.1.2 on 2020-10-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0002_dummy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='booking_created',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='from_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='to_date',
            field=models.TextField(),
        ),
    ]
